### ISSUE TITLE
Why float?

### ISSUE THREAD

**Issue by yasheena** [macaba/ESP32AudioLibrary#1]
Hello,

I'm a fan of ESP-IDF and actually I search a good audio library. First I found the Teensy Audio Library and was excited about the many features. I thought to adapt it for the ESP32. Then I found your library and saw that you already had done some of this work. But I'm also interested in several of the not converted modules and would invest time to do that. But before I start I have a question: What is the reason for changing  from int16_t to float? I would think it's easier to adapt the code without such a change. So I'm very interested which advantage you see in this change.

**Comment by tschrama** [comment]
Intermediate processing results benifit from better number precision. Eager to try this library out.

**Comment by macaba** [comment]
As tschrama said - float gives more dynamic range in intermediate processing. Example: mixer with a lot of loud inputs, going into compressor; the intermediate data between mixer and compressor is likely to exceed 1.0 (or whatever the maximum value would be in a non-float system), and the compressor output brings it back into range.
