### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by jvpasinatto** [macaba/ESP32AudioLibrary#2]
Hello, by any chance this project is still alive?
I don't have much C++ experience but I can help. I particulary interested in the filter and synth_waveform files from Teensy library that are not compatible with ESP32 yet.
If not, any tips on how to do it?

**Comment by serkansmg** [comment]
hi, i need commercial support/development for your library.. if you are interested please send me msg serkan@smg.com.tr
